controllers:
    resource: ../src/Controller/
    type: attribute

# Removed routes from here after using annotations
# app_lucky_number:
#   path: /lucky/number
#   controller: App\Controller\LuckyController::number